using System.Reflection;
using System.Text;

namespace Havit.SourceGenerators.StrongApiStringLocalizers.SourceBuilders;

internal static class StringBuilderExtensions
{
	public static StringBuilder AppendAutoGeneratedDocumenationCommentLine(this StringBuilder builder)
	{
		return builder.AppendLine("// <auto-generated />");
	}

	public static StringBuilder AppendGeneratedCodeAttributeLine(this StringBuilder builder)
	{
		return builder.AppendLine($"[GeneratedCode(\"{nameof(Havit)}.{nameof(SourceGenerators)}.{nameof(StrongApiStringLocalizers)}.{nameof(StrongApiStringLocalizersGenerator)}\", \"{typeof(StringBuilderExtensions).Assembly.GetName().Version}\")]");
	}
}
