using System;
using System.Threading.Tasks;
using Havit.Blazor.Components.Web.Infrastructure;
using Microsoft.AspNetCore.Components;

namespace Havit.Blazor.Components.Web.Bootstrap
{
	/// <summary>
	/// Wizard Step component
	/// </summary>
	public partial class HxWizardStep : ComponentBase, IDisposable, IRenderNotificationComponent
	{
		/// <summary>
		/// ID of the step (<see cref="HxWizard.ActiveStepId"/>).
		/// Autogenerated GUID if not set.
		/// </summary>
		[Parameter] public string Id { get; set; } = "hx" + Guid.NewGuid().ToString("N");

		/// <summary>
		/// Name of the step for HxWizzard navigator.
		///</summary>
		[Parameter] public string Name { get; set; }

		/// <summary>
		/// Content of the step.
		/// </summary>
		[Parameter] public RenderFragment ChildContent { get; set; }

		[CascadingParameter(Name = HxWizard.StepsRegistrationCascadingValueName)] public CollectionRegistration<HxWizardStep> StepsRegistration { get; set; }

		RenderedEventHandler IRenderNotificationComponent.Rendered { get; set; }

		protected override void OnInitialized()
		{
			StepsRegistration.Register(this);
		}

		protected override void OnAfterRender(bool firstRender)
		{
			base.OnAfterRender(firstRender);

			((IRenderNotificationComponent)this).Rendered?.Invoke(this, firstRender);
		}

		public void Dispose()
		{
			StepsRegistration.Unregister(this);
		}
	}
}