namespace Havit.Blazor.Components.Web.Bootstrap;

/// <summary>
/// Bootstrap icon.
/// </summary>
/// <remarks>
/// To update bootstrap icons, perform the following steps:
/// - Update wwwroot\fonts\bootstrap-icons.woff
/// - Update wwwroot\fonts\bootstrap-icons.woff2
/// - Update wwwroot\bootstrap-icons.css
/// - Update bootstrap-icons.json in this folder.
/// BootstrapIcon.Xy properties will be generated by a source generator.
/// </remarks>
public partial class BootstrapIcon : IconBase
{
	/// <inheritdoc cref="IconBase.RendererComponentType" />
	public override Type RendererComponentType => typeof(HxBootstrapIcon);

	/// <summary>
	/// Name of the bootstrap icon.
	/// </summary>
	public string Name { get; set; }

	/// <summary>
	/// Private constructor.
	/// </summary>
	private BootstrapIcon(string name)
	{
		Name = name;
	}

	// Next members are generated using a source generator.
	// The source for the generator is the bootstrap-icons.json file located next to this one.
}
