using System.ComponentModel;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.JSInterop;

namespace Havit.Blazor.Components.Web.ECharts;

/// <summary>
/// Component for convenient rendering of Apache ECharts.
/// </summary>
public partial class HxEChart : IAsyncDisposable
{
	private static readonly JsonSerializerOptions s_JsonSerializerOptions;

	/// <summary>
	/// Unique identifier for the HTML element representing the chart.
	/// </summary>
	[Parameter] public string ChartId { get; set; } = $"hx-echart-{Guid.NewGuid()}";

	/// <summary>
	/// Options for the chart. See <a href="https://echarts.apache.org/en/option.html">ECharts Option</a> for more details.
	/// </summary>
	[Parameter, EditorRequired] public object Options { get; set; }

	/// <summary>
	/// The height of the chart. Default is <c>400px</c>.
	/// Set to an empty string (or <c>null</c>) to omit the <c>height</c> declaration and let the surrounding CSS (e.g. a flex parent) drive the height.
	/// </summary>
	/// <remarks>
	/// Note the Razor syntax: <c>Height=""</c> or <c>Height="@null"</c>. Plain <c>Height="null"</c> passes the literal string <c>null</c>
	/// (which would render an invalid <c>height: null</c> declaration).
	/// </remarks>
	[Parameter] public string Height { get; set; } = "400px";

	/// <summary>
	/// The width of the chart (rendered as both <c>min-width</c> and <c>max-width</c> of the container). Default is <c>100%</c>.
	/// Set to an empty string to omit the width declarations and let the surrounding CSS drive the width.
	/// </summary>
	[Parameter] public string Width { get; set; }

	/// <summary>
	/// Additional CSS classes for the chart container.
	/// </summary>
	[Parameter] public string CssClass { get; set; }

	/// <summary>
	/// Indicates whether the chart should automatically resize. Default is <c>false</c>.
	/// </summary>
	[Parameter] public bool AutoResize { get; set; } = false;

	/// <summary>
	/// Invoked when the chart is clicked.
	/// </summary>
	[Parameter] public EventCallback<EChartClickEventArgs> OnClick { get; set; }

	/// <summary>
	/// Invoked when the user moves the axis pointer (e.g., when hovering over a chart).
	/// </summary>
	[Parameter] public EventCallback<EChartAxisPointerUpdatedEventArgs> OnAxisPointerUpdated { get; set; }

	/// <summary>
	/// Additional attributes to be splatted onto the underlying chart container <c>div</c>.
	/// </summary>
	/// <remarks>
	/// The attributes are splatted after the <c>style</c> attribute generated by the component,
	/// therefore passing <c>style</c> here replaces the <see cref="Width"/>/<see cref="Height"/> declarations.
	/// An <c>id</c> passed here takes precedence over <see cref="ChartId"/> (and is used for the JavaScript interop as well).
	/// </remarks>
	[Parameter(CaptureUnmatchedValues = true)] public Dictionary<string, object> AdditionalAttributes { get; set; }

	[Inject] protected IJSRuntime JSRuntime { get; set; }

	private IJSObjectReference _jsModule;
	private DotNetObjectReference<HxEChart> _dotNetObjectReference;
	private byte[] _currentOptionsHash;
	private string _optionsToApply;
	private bool _shouldSetupChartOnAfterRender;
	private bool _disposed;

	static HxEChart()
	{
		s_JsonSerializerOptions = new JsonSerializerOptions()
		{
			PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
			DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
			Converters =
			{
				new JsonStringEnumConverter(JsonNamingPolicy.CamelCase),
				new JSFuncConverter(),
			}
		};
	}

	public HxEChart()
	{
		_dotNetObjectReference = DotNetObjectReference.Create(this);
	}

	/// <summary>
	/// The <c>id</c> the container is actually rendered with (and therefore the one the JavaScript interop has to use).
	/// An <c>id</c> coming from <see cref="AdditionalAttributes"/> wins, as it is splatted after the <c>id</c> attribute generated by the component.
	/// </summary>
	/// <remarks>
	/// The keys are matched case-insensitively on purpose: Blazor eliminates the duplicate <c>id</c> attribute case-insensitively,
	/// so an <c>Id</c>/<c>ID</c> key wins in the rendered markup just like a lowercase <c>id</c> does.
	/// We cannot rely on the dictionary comparer here - the framework builds the splatted dictionary with
	/// <see cref="StringComparer.OrdinalIgnoreCase"/>, but a consumer passing <see cref="AdditionalAttributes"/> explicitly
	/// may well use a case-sensitive one (which can therefore even hold several keys differing only by casing).
	/// The last match is taken for the same reason - Blazor keeps the last of the duplicates in render order.
	/// </remarks>
	private string ChartIdEffective
	{
		get
		{
			var splattedId = AdditionalAttributes?
				.Where(attribute => String.Equals(attribute.Key, "id", StringComparison.OrdinalIgnoreCase))
				.Select(attribute => attribute.Value?.ToString())
				.LastOrDefault();

			return String.IsNullOrEmpty(splattedId) ? ChartId : splattedId;
		}
	}

	private string GetContainerStyle()
	{
		var widthEffective = Width ?? "100%";
		var declarations = new List<string>(3);
		if (!String.IsNullOrEmpty(widthEffective))
		{
			declarations.Add($"min-width: {widthEffective}");
		}
		if (!String.IsNullOrEmpty(Height))
		{
			declarations.Add($"height: {Height}");
		}
		if (!String.IsNullOrEmpty(widthEffective))
		{
			declarations.Add($"max-width: {widthEffective}");
		}

		return declarations.Count == 0 ? null : String.Join("; ", declarations) + ";";
	}

	protected override void OnParametersSet()
	{
		if (Options is not null)
		{
			var newOptions = JsonSerializer.SerializeToUtf8Bytes(Options, s_JsonSerializerOptions);
			Span<byte> newOptionsHash = stackalloc byte[SHA256.HashSizeInBytes];
			SHA256.HashData(newOptions, newOptionsHash);

			if ((_currentOptionsHash is null) || !newOptionsHash.SequenceEqual(_currentOptionsHash))
			{
				_shouldSetupChartOnAfterRender = true;
				_currentOptionsHash = newOptionsHash.ToArray();
				_optionsToApply = Encoding.UTF8.GetString(newOptions);
			}
		}
	}

	protected override async Task OnAfterRenderAsync(bool firstRender)
	{
		if (!_shouldSetupChartOnAfterRender)
		{
			return;
		}

		// Claim the flag and the payload before the first await: a re-render occurring while this pass
		// is suspended queues another OnAfterRenderAsync pass which would otherwise enter here as well
		// and, once this pass has released the payload, hand null to setupChart.
		_shouldSetupChartOnAfterRender = false;
		var optionsToApply = _optionsToApply;
		_optionsToApply = null; // release the serialized JSON, only the hash is kept for change detection

		try
		{
			await EnsureJsModuleAsync();
			if (_disposed)
			{
				return;
			}

			await _jsModule.InvokeVoidAsync("setupChart", ChartIdEffective, _dotNetObjectReference, optionsToApply, AutoResize, OnAxisPointerUpdated.HasDelegate);
		}
		catch
		{
			// restore the pending setup so the next render retries after a transient interop failure
			// (unless newer options arrived in the meantime - those take precedence)
			if (!_shouldSetupChartOnAfterRender)
			{
				_shouldSetupChartOnAfterRender = true;
				_optionsToApply = optionsToApply;
			}
			throw;
		}
	}

	private async Task EnsureJsModuleAsync()
	{
#if NET9_0_OR_GREATER
		_jsModule ??= await JSRuntime.InvokeAsync<IJSObjectReference>("import", Assets["./_content/Havit.Blazor.Components.Web.ECharts/HxEChart.js"]);
#else
		_jsModule ??= await JSRuntime.InvokeAsync<IJSObjectReference>("import", "./_content/Havit.Blazor.Components.Web.ECharts/HxEChart.js");
#endif
	}

	[JSInvokable("HandleClick")]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public async Task HandleClick(EChartClickEventArgs eventParams)
	{
		await OnClick.InvokeAsync(eventParams);
	}

	[JSInvokable("HandleAxisPointerUpdate")]
	[EditorBrowsable(EditorBrowsableState.Never)]
	public async Task HandleAxisPointerUpdate(EChartAxisPointerUpdatedEventArgs value)
	{
		await OnAxisPointerUpdated.InvokeAsync(value);
	}

	async ValueTask IAsyncDisposable.DisposeAsync()
	{
		await DisposeAsyncCore();

		//Dispose(disposing: false);
	}

	protected virtual async ValueTask DisposeAsyncCore()
	{
		_disposed = true;

		if (_jsModule != null)
		{
			try
			{
				await _jsModule.InvokeVoidAsync("dispose", ChartIdEffective);
				await _jsModule.DisposeAsync();
			}
			catch (JSDisconnectedException)
			{
				// NOOP
			}
		}

		_dotNetObjectReference?.Dispose();
	}

	/// <summary>
	/// Represents a JavaScript function to be passed to the ECharts options.
	/// </summary>
	/// <param name="RawCode">The raw JavaScript code.</param>
	public record JSFunc(string RawCode);

	private class JSFuncConverter : JsonConverter<JSFunc>
	{
		public override JSFunc Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
		{
			throw new NotSupportedException();
		}

		public override void Write(Utf8JsonWriter writer, JSFunc value, JsonSerializerOptions options)
		{
			writer.WriteRawValue(value.RawCode, true);
		}
	}
}
