namespace Havit.Blazor.Components.Web.Bootstrap;

/// <summary>
/// <see href="https://getbootstrap.com/docs/5.3/components/navbar/">Bootstrap 5 Navbar</see> component - a responsive navigation header.<br/>
/// Provides support for branding, navigation, and more, including support for the collapse plugin.<br />
/// For full documentation and demos, visit: <see href="https://havit.blazor.eu/components/HxNavbar">https://havit.blazor.eu/components/HxNavbar</see>
/// </summary>
public partial class HxNavbar
{
	/// <summary>
	/// Color (background).
	/// The default value is <see cref="ThemeColor.None"/>.
	/// </summary>
	[Parameter] public ThemeColor Color { get; set; } = ThemeColor.None;

	/// <summary>
	/// Bootstrap theme (color mode) applied to the navbar.
	/// The default value is <see cref="ColorMode.Auto"/> (none).
	/// </summary>
	[Parameter] public ColorMode ColorMode { get; set; }

	/// <summary>
	/// Responsive expand setting (breakpoint) for <see cref="HxNavbar"/>.<br/>
	/// The default value is <see cref="NavbarExpand.LargeUp"/>.
	/// </summary>
	[Parameter] public NavbarExpand Expand { get; set; } = NavbarExpand.LargeUp;

	/// <summary>
	/// Element ID.
	/// (An autogenerated GUID is used if not set explicitly.)
	/// </summary>
	[Parameter] public string Id { get; set; } = "hx" + Guid.NewGuid().ToString("N");

	/// <summary>
	/// Additional CSS class.
	/// </summary>
	[Parameter] public string CssClass { get; set; }

	/// <summary>
	/// Container CSS class. The default value is <c>container-fluid</c>.
	/// </summary>
	[Parameter] public string ContainerCssClass { get; set; } = "container-fluid";

	/// <summary>
	/// Content of the navbar.
	/// </summary>
	[Parameter] public RenderFragment ChildContent { get; set; }

	protected internal string GetDefaultCollapseId()
	{
		return Id + "-collapse";
	}

	protected virtual string GetExpandCssClass()
	{
		return Expand switch
		{
			NavbarExpand.Always => "navbar-expand",
			NavbarExpand.SmallUp => "navbar-expand-sm",
			NavbarExpand.MediumUp => "navbar-expand-md",
			NavbarExpand.LargeUp => "navbar-expand-lg",
			NavbarExpand.ExtraLargeUp => "navbar-expand-xl",
			NavbarExpand.XxlUp => "navbar-expand-xxl",
			NavbarExpand.Never => null,
			_ => throw new InvalidOperationException($"Unknown {nameof(NavbarExpand)} value {Expand}.")
		};
	}

	protected virtual string GetCssClass()
	{
		return CssClassHelper.Combine(
			"navbar",
			GetExpandCssClass(),
			Color.ToBackgroundColorCss(),
			CssClass);
	}
}
